# Top Makefile for Qt 4 projects on Linux
# with g++ version > 4.1
QMAKE := qmake
# Qt4 Makefile
MAKEFILE_QT = Makefile.qt

.PHONY: qt debug release clean distclean

all: qt
	$(MAKE) -f$(MAKEFILE_QT) -j2

debug: qt
	$(MAKE) $@ -f$(MAKEFILE_QT) -j2

release: qt
	$(MAKE) $@ -f$(MAKEFILE_QT) -j2

qt: 
	$(QMAKE) -project
	$(QMAKE) -o $(MAKEFILE_QT)

clean:
	$(MAKE) -f$(MAKEFILE_QT) $@
	$(RM) $(MAKEFILE_QT)

distclean:
	$(MAKE) -f$(MAKEFILE_QT) $@
	$(RM) $(MAKEFILE_QT)
